name: Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        chmod +x install_dependencies.sh
        ./install_dependencies.sh

    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11

    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v1.13
      with:
        cmake-version: '3.28.0'

    - name: Configure
      run: cmake --preset VcpkgDebug

    - name: Build
      run: cmake --build build/debug --config Debug --parallel

    - name: Run tests
      run: |
        cmake --build build/debug --config Debug --target test_exe
        ./build/debug/test_exe

    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: logs
        path: logs/
        retention-days: 30 